module.exports={
    PRODUCT_COLLECTION:'product',
    USER_COLLECTION:'user',
    CART_COLLECTION:'cart',
    ORDER_COLLECTION:'order',
    ADMIN_COLLECTION:'admin',
    USER_PRODUCTS_COLLECTION:'user_products',
    MESSAGE_COLLECTION:'messages'
}